'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CMS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property appointment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appointment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Diagnose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Diagnose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!-- saved from url=(0046)http://www.jonathantneal.com/examples/invoice/ --&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;style&gt;article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}&lt;/style&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''		&lt;title&gt;Diagnose Report&lt;/title&gt;
        '''
        '''		
        '''    &lt;style  type=&quot;text/css&quot;&gt;
        '''        *
        '''{
        '''	borde [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Digreport() As String
            Get
                Return ResourceManager.GetString("Digreport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!-- saved from url=(0046)http://www.jonathantneal.com/examples/invoice/ --&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;style&gt;article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}&lt;/style&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''		&lt;title&gt;Invoice&lt;/title&gt;
        '''    &lt;style media=&quot;print&quot; type=&quot;text/css&quot;&gt;
        '''        * { -webkit-p [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Invoice() As String
            Get
                Return ResourceManager.GetString("Invoice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Payment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Payment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!-- saved from url=(0046)http://www.jonathantneal.com/examples/invoice/ --&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;style&gt;article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}&lt;/style&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Test Request&lt;/title&gt;
        '''
        '''		
        '''    &lt;style  type=&quot;text/css&quot;&gt;
        '''        *
        '''{
        '''	border: 0; [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Pr() As String
            Get
                Return ResourceManager.GetString("Pr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;tr&gt;&lt;td align=&quot;center&quot;&gt;mednum&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;medname&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;meddesc&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;medintake&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;midfreq&lt;/td&gt;&lt;td align=&quot;center&quot;&gt;meddur&lt;/td&gt;&lt;/tr&gt;.
        '''</summary>
        Public ReadOnly Property prerow() As String
            Get
                Return ResourceManager.GetString("prerow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!-- saved from url=(0046)http://www.jonathantneal.com/examples/invoice/ --&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;style&gt;
        '''    article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}
        '''	
        '''	#hide {
        '''	color: #FFF;
        '''}
        '''    &lt;/style&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''		&lt;title&gt;Diagnose Report&lt;/title&gt;
        '''
        '''		
        '''    &lt;st [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Prescription() As String
            Get
                Return ResourceManager.GetString("Prescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property queue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("queue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Reports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Save_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;!-- saved from url=(0046)http://www.jonathantneal.com/examples/invoice/ --&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;style&gt;article,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio[controls],canvas,video{display:inline-block}[hidden],audio{display:none}mark{background:#FF0;color:#000}&lt;/style&gt;
        '''		&lt;meta charset=&quot;utf-8&quot;&gt;
        '''&lt;title&gt;Test Request&lt;/title&gt;
        '''
        '''		
        '''    &lt;style  type=&quot;text/css&quot;&gt;
        '''        *
        '''{
        '''	border: 0; [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property SL() As String
            Get
                Return ResourceManager.GetString("SL", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
